config/routes.rb
Listenit::Application.routes.draw do

  get "devise/registrationcontroller"
  get "sessions/new"

  devise_for :admins
  devise_for :users

  root :to => "home#index"

  match '/signout', :to => 'sessions#destroy'
  match '/signin',  :to => 'sessions#new'
  match '/signup',  :to => 'users#sign_up'
  match '/users',   :to => 'users#index'
  match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
  match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

  get 'tags/:tag', to: 'audios#index', as: :tag

  resources :tags

  resources :audios do
    member { post :vote }
    member do
      get :download
    end
  end

end

app/models/audio.rb
class Audio < ActiveRecord::Base

  has_many :tags
  belongs_to :user
  attr_accessor :tag_list
  attr_accessible :audio, :description, :content, :tag_list, :audio_file_name, :user_id
  before_save :extract_metadata
  serialize :metadata

  has_attached_file :audio
  validates_attachment_presence :audio
  validates :tag_list, :length => {:maximum => 8}
  validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
  has_reputation :votes, source: :user, aggregated_by: :sum
  searchable do
    text :audio, :description, :tag_list, :audio_file_name
  end

  def tag_list
    @tag_list || tags.map(&:name).join(", ")
  end

  def assign_tags
    if @tag_list
      self.tags = @tag_list.split(/,/).uniq.map do |name|
        Tag.where(:name => name).first || Tag.create(:name => name)
      end
    end
  end
  acts_as_taggable
  def author_tokens=(ids)
    self.tag_ids = ids.split(",")
  end

 def display_name
    @display_name ||= if audio? && metadata?
                        artist, title = metadata.values_at('artist', 'title')
                        title.present? ? [title, artist].compact.join(' - ').force_encoding('UTF-8') : audio_file_name
                      else
                        audio_file_name
                      end
  end

  private

  def extract_metadata
    return unless audio?
    path = audio.queued_for_write[:original].path
    open_opts = { :encoding => 'utf-8' }
    Mp3Info.open(path, open_opts) do |mp3info|
      self.metadata = mp3info.tag
    end
  end
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController

  def index
    if params[:tag]
      @audios = Audio.tagged_with(params[:tag])
    else
      @audios = Audio.all
      @search = Audio.search do
        fulltext params[:search]
      end
      @audios = @search.results
      @audios_votes = Audio.find_with_reputation(:votes, :all, order: 'votes desc')
    end
  end


  def vote
    value = params[:type] == "up" ? 1 : -1
    @audio = Audio.find(params[:id])
    @audio.add_evaluation(:votes, value, current_user)
    redirect_to :back, notice: t(:vote_thanks)
  end

  def download
    @audio = Audio.find(params[:id])
    a = Audio.first
    file_path = @audio.audio_file_name
    if !file_path.nil?

      send_file "/public/audios/audios/000/000/082/original/#{a.audio_file_name}", :x_sendfile => true
    else
      redirect_to audio_url
    end
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
    @audio = Audio.find(params[:id])
      respond_to do |format|
        format.json {render :json => resource }
        format.html {render :action => :show}
        format.any {
          path = resource.file.path(params[:style] || params[:format])
          head(:not_found) and return unless File.exist?(path)
          send_file path,
                    :filename => resource.file_file_name,
                    :disposition => "inline",
                    :type => request.format
        }
      end
  end

  # GET /audios/new
  # GET /audios/new.json
  def new
    @title = t(:new_audio)
    @audio = Audio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @audio }
    end
  end

  # GET /audios/1/edit
  def edit
    @audio = Audio.find(params[:id])
  end

  # POST /audios
  # POST /audios.json
  def create
    @audio = Audio.new(params[:audio])
    @audio.user_id = current_user.id
    respond_to do |format|
      if @audio.save
        format.html { redirect_to @audio, notice: t(:audio_confirm) }
        format.json { render json: @audio, status: :created, location: @audio }
      else
        format.html { render action: "new" }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end

    end
  end

  # PUT /audios/1
  # PUT /audios/1.json
  def update
    @audio = Audio.find(params[:id])

    respond_to do |format|
      if @audio.update_attributes(params[:audio])
        format.html { redirect_to @audio, notice: 'Audio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @audio.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @audio = Audio.find(params[:id])
    @audio.destroy
    respond_to do |format|
      flash[:success] = t(:audio_deleted)
      format.html { redirect_to  "/users/#{current_user.id}" }
      format.json { head :no_content }
    end
  end

end

app/views/audios/_form.html.erb
<%= form_for(@audio) do |f| %>
    <% if @audio.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@audio.errors.count, "error") %> prohibited this audio from being saved:</h2>
          <ul>
            <% @audio.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.file_field :audio %>
    </div>
    <div class="field">
      <%= f.label :tag_list %><br />
      <%= f.text_field :tag_list %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description %>
    </div>
    <div class="button">
      <%= f.submit %>
    </div>
<% end %>

app/views/audios/_player.html.erb
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=0.6" name="viewport">

  <%= stylesheet_link_tag "player", :media => "all" %>
</head>
<h1><%= @title %></h1>
<body>
<div id="wrapper">
  <h1>wait what — notorious xx <em>(2009)</em></h1>
  <audio preload></audio>
  <div class="track-details">
    Juicy-r <em>by</em> Wait What
  </div>
  <ol>
    <li><a href="#" data-src="/public/Tricky_–_Bombing_Bastards.mp3">dead wrong intro</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/02-juicy-r.mp3">juicy-r</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/03-its-all-about-the-crystalizabeths.mp3">it's all about the crystalizabeths</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/04-islands-is-the-limit.mp3">islands is the limit</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/05-one-more-chance-for-a-heart-to-skip-a-beat.mp3">one more chance for a heart to skip a beat</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/06-suicidal-fantasy.mp3">suicidal fantasy</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/07-everyday-shelter.mp3">everyday shelter</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/08-basic-hypnosis.mp3">basic hypnosis</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/09-infinite-victory.mp3">infinite victory</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/10-the-curious-incident-of-big-poppa-in-the-nighttime.mp3">the curious incident of big poppa in the nighttime</a></li>
    <li><a href="#" data-src="http://s3.amazonaws.com/audiojs/11-mo-stars-mo-problems.mp3">mo stars mo problems</a></li>
  </ol>
</div>
</body>

app/views/audios/edit.html.erb
<h1><%= t(:editing) %></h1>

<%= render 'form' %>

<%= link_to 'Show', @audio %> |
<%= link_to 'Back', audios_path %>

app/views/audios/index.html.erb
<section id="tables">
  <table  class="table table-bordered table-striped table-hover paginated">
    <thead>
    <tr>
      <th><%= t(:song_name) %></th>
      <th><%= t(:tags) %></th>
    </tr>
    </thead>
    <% @audios.each do |audio| %>
        <tr>
          <td>
            <%= link_to image_tag('Download_icon_images.jpg') %>
            <%= link_to image_tag('add_7580.png')%>
            <%= audio.display_name %>
            <div class="bubbleInfo">
              <div id="download" class="trigger">Info</div>
              <table style="opacity: 0; top: -50px; left: -33px; display: none;" id="dpop" class="popup">
                <td>Title: <%= audio.metadata['title'] %> </td>
                <td>Artist: <%= audio.metadata['artist'] %> </td>
                <td>Album: <%= audio.metadata['album'] %> </td>
                <td>Year: <%= audio.metadata['year'] %> </td>
                <td><%= audio.description %></td>
                <div class="haiku">
                  <em>
                    --<%= audio.user.name %>
                    |<%= pluralize audio.reputation_for(:votes).to_i, "vote" %>
                    <% if current_user && !current_user.voted_for?(audio) %>
                        | <%= link_to "up", vote_audio_path(audio, type: "up"), method: "post" %>
                        | <%= link_to "down", vote_audio_path(audio, type: "down"), method: "post" %>
                    <% end %>
                  </em>
                </div>
              </table>
            </div>
          </td>
          <td><%= raw audio.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        </tr>
    <% end %>
  </table>
</section>

app/views/audios/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', audios_path %>

app/views/audios/show.html.erb
<p>
  <%= @audio.display_name %>
</p>


<%= link_to 'Edit', edit_audio_path(@audio) %> |
<%= link_to 'Back', audios_path %>