config/routes.rb
Listenit::Application.routes.draw do

  get "devise/registrationcontroller"
  get "sessions/new"

  devise_for :admins
  devise_for :users

  root :to => "home#index"

  match '/signout', :to => 'sessions#destroy'
  match '/signin',  :to => 'sessions#new'
  match '/signup',  :to => 'users#sign_up'
  match '/users',   :to => 'users#index'
  match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
  match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

  get 'tags/:tag', to: 'audios#index', as: :tag

  resources :tags

  resources :audios do
    member { post :vote }
    member do
      get :download
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


  attr_accessible :name , :email, :password, :password_confirmation, :remember_me, :confirmed_at, :admin,
                  :confirmation_token, :locale, :style_id
  has_many :audios
  belongs_to :styles

  has_reputation :votes, source: {reputation: :votes, of: :audios}, aggregated_by: :sum

  has_many :evaluations, class_name: ReputationSystem::Evaluation, as: :source

  def voted_for?(audio)
    evaluations.where(target_type: audio.class, target_id: audio.id).present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
  def index
    @users = User.all
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t(:user_destroy)
    redirect_to users_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def my_page_link
    if user_signed_in?
      link_to t(:my_page), "/users/#{current_user.id}"
    end
  end

  def user_register_link
    s = ''.html_safe
    s += '<li>'.html_safe
    if user_signed_in?
      s += link_to(t(:edit_user), edit_user_registration_path)
      s += link_to(t(:logout), destroy_user_session_path)
    elsif admin_signed_in?
      s += link_to(t(:users_list), users_path)
      s +=  link_to(t(:logout), destroy_admin_session_path)
    else
      s +=  link_to(t(:sign_up), new_user_registration_path)
      s += link_to(t(:sign_in), new_user_session_path)
      s += link_to(t(:admin) , new_admin_session_path)
    end
  end

  def stats
    g = Gruff::Line.new('580x210')
    g.theme = {
        :colors => ['#ff6600', '#3bb000', '#1e90ff', '#efba00', '#0aaafd'],
        :marker_color => '#aaa',
        :background_colors => ['#eaeaea', '#fff']
    }

    g.hide_title = true
    g.font = File.expand_path('path/to/font.ttf', RAILS_ROOT)

    range = "created_at #{(12.months.ago.to_date..Date.today).to_s(:db)}"
    @users = User.count(:all, :conditions => range, :group => "DATE_FORMAT(created_at, '%Y-%m')", :order =>"created_at ASC")
    @votes = Vote.count(:all, :conditions => range, :group => "DATE_FORMAT(created_at, '%Y-%m')", :order =>"created_at ASC")
    @bookmarks = Bookmark.count(:all, :conditions => range, :group => "DATE_FORMAT(created_at, '%Y-%m')", :order =>"created_at ASC")

    # Take the union of all keys & convert into a hash {1 => "month", 2 => "month2"...}
    # - This will be the x-axis.. representing the date range
    months = (@users.keys | @votes.keys | @bookmarks.keys).sort
    keys = Hash[*months.collect {|v| [months.index(v),v.to_s] }.flatten]

    # Plot the data - insert 0's for missing keys
    g.data("Users", keys.collect {|k,v| @users[v].nil? ? 0 : @users[v]})
    g.data("Votes", keys.collect {|k,v| @votes[v].nil? ? 0 : @votes[v]})
    g.data("Bookmarks", keys.collect {|k,v| @bookmarks[v].nil? ? 0 : @bookmarks[v]})

    g.labels = keys

    send_data(g.to_blob, :disposition => 'inline', :type => 'image/png', :filename => "site-stats.png")
  end
end

app/views/users/_all_music.html.erb
<%= link_to 'New Audio', new_audio_path %>
<section id="tables">
  <table  class="table table-bordered table-striped table-hover paginated">
    <thead>
    <tr>
      <th><%= t(:song_name) %></th>
      <th><%= t(:tags) %></th>
    </tr>
    </thead>
       <% Audio.all.each do |audio| %>
        <tr>

        <td> <%= link_to image_tag('Download_icon_images.jpg') %>
             <%= link_to image_tag('add_7580.png')%>
             <%= audio.display_name %>
          <div class="bubbleInfo">
            <div id="download" class="trigger">Info</div>
            <table style="opacity: 0; top: -50px; left: -33px; display: none;" id="dpop" class="popup">
              <td>Title: <%= audio.metadata['title'] %> </td>
              <td>Artist: <%= audio.metadata['artist'] %> </td>
              <td>Album: <%= audio.metadata['album'] %> </td>
              <td>Year: <%= audio.metadata['year'] %> </td>
              <td><%= audio.description %></td>
              <div class="haiku">

                <em>
                  --<%= audio.user.name %>
                    |<%= pluralize audio.reputation_for(:votes).to_i, "vote" %>
                  <% if current_user && !current_user.voted_for?(audio) %>
                      | <%= link_to "up", vote_audio_path(audio, type: "up"), method: "post" %>
                      | <%= link_to "down", vote_audio_path(audio, type: "down"), method: "post" %>
                  <% end %>
                </em>
              </div>
            </table>
          </div>
        </td>
        <td><%= raw audio.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
        </tr>
    <% end %>
    </table>
</section>

app/views/users/_playlist.html.erb
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=0.6" name="viewport">
  <%= stylesheet_link_tag "player", :media => "all" %>
</head>
<body>
  <ol>
    <% current_user.audios.each do |audio|  %>
        <!-- <div class="track-details">
          <%= audio.metadata['title'] %> <em>by</em> <%=  audio.metadata['artist']%>
        </div>-->
        <li><a href="#" data-src=<%= audio.audio.url %>><%= audio.display_name %></a></li>
    <% end %>
  </ol>
</body>

app/views/users/_user_page.html.erb
<div class="row">
  <div class="span4">

    <h3 id="tabs"><%= current_user.name %>'s <%= t(:profile) %></h3>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#A" data-toggle="tab"><%= t(:all_music) %></a></li>
      <li><a href="#C" data-toggle="tab"><%= t(:my_playlist) %></a></li>
      <li><a href="#D" data-toggle="tab"><%= t(:my_tracks) %></a></li>
    </ul>
    <div class="tabbable">
      <div class="tab-content">
        <div class="tab-pane active" id="A">
          <%= render 'users/all_music' %>
          </div>
        <div class="tab-pane" id="C">
          <%= render 'users/playlist' %>
        </div>
        <div class="tab-pane" id="D">
         <%= render 'users/users_own_tracks' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_users_own_tracks.erb
<section id="tables">
  <table  class="table table-bordered table-striped table-hover paginated">
    <thead>
    <tr>
      <th>Song name</th>
      <th>Tags</th>
      <th>Tools</th>
    </tr>
    </thead>
    <tbody>
    <% current_user.audios.each do |audio| %>
        <tr>
          <td>
            <%= link_to image_tag('Download_icon_images.jpg')%>
            <%= link_to image_tag('add_7580.png')%>
            <%= audio.display_name %>
            <div class="bubbleInfo">
              <div id="download" class="trigger">Info</div>
              <table style="opacity: 0; top: -50px; left: -33px; display: none;" id="dpop" class="popup">
                <td>Title: <%= audio.metadata['title'] %> </td>
                <td>Artist: <%= audio.metadata['artist'] %> </td>
                <td>Album: <%= audio.metadata['album'] %> </td>
                <td>Year: <%= audio.metadata['year'] %> </td>
                <td><%= audio.description %></td>
              </table>
            </div>
          </td>
          <td><%= raw audio.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
          <td><%= link_to 'Show', audio %>
                <%= link_to 'Edit', edit_audio_path(audio) %>
                <%= link_to 'Destroy', audio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </table>
 </section>

app/views/users/index.html.erb
<h1>All users</h1>
<ul class="users">
  <% if admin_signed_in? %>
      <table>
      <% @users.each do |user| %>
          <tr>
        <td><%= user.name%>
          <%= link_to t(:delete), user_path(user), :method => :delete, :confirm => "You sure?",
                      :title => "Delete #{user.name}" %> </td> </tr>
    <% end %>

  <% end %>
  </table>
</ul>

app/views/users/show.html.erb
<%= render 'user_page' %>